### ISSUE TITLE
Envoy Fundamentals Continued

### ISSUE THREAD

**Issue by cecilphillip** [tetratelabs/istio-weekly#7]
This video on [Envoy fundamentals](https://www.youtube.com/watch?v=f0QEHEm9ERc) is a great getting started resources. The envoy docs are really thorough by can be a little challenging to navigate through to find the things that I actually need. Please do more of these envoy fundamentals (w/o kubernetes) videos. Here are some topics I'd like to see
* dynamic configuration of upstream endpoints
* setting up envoy sidecars + front proxy
* tracing envoy sidecars with zipkin

**Comment by cecilphillip** [comment]
Please 🙂

**Comment by peterj** [comment]
Hi @cecilphillip! Not sure if you saw, but I've recorded a full Envoy course since then :) The labs cover some of the topics you mention above. 

https://academy.tetrate.io/courses/envoy-fundamentals

**Comment by cecilphillip** [comment]
@peterj No I did not! Thanks. I'll close this issue then
